[package]
name = "moonlite"
version = "0.1.0"
edition = "2021"

[dependencies]
name-variant = "0.1.0"
owo-colors = "4.0.0"
ariadne = { version = "0.5.0", features = ["auto-color"] }
dashmap = "6.0.1"
int-enum = "1.1.2"
